default:
  adapter: mysql2
  database: superstars
  username: sinatra
  password: workspace
  host: localhost


development :
  adapter: mysql2
  database: superstars
  username: sinatra
  password: workspace
  host: localhost

production:
  adapter: mysql2
  database: superstars
  username: sinatra
  password: workspace
  host: localhost